#!/usr/bin/env bash
#
# Production deployment wizard for Seminar Tool.
# Walks a human through every step needed to deploy to Vercel + Supabase.
#
# Generated by the /wizard skill.
#
# Usage: bash scripts/deploy-production.sh
#
# The wizard is idempotent: re-running it picks up values already saved to
# the staging file (default .env.deploy) and skips completed stages. The
# staging file is gitignored (.env.*) and never loaded by Next.js, so it
# cannot interfere with local development.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env.deploy}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

_upsert_vercel_env() {
  local key="$1" value="$2" env="$3"
  local cmd
  cmd=$(vercel_cmd)
  if [[ -n "$cmd" ]]; then
    if $cmd env add "$key" "$env" --force <<< "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s Vercel env %s (%s)\n' "$GREEN" "$RESET" "$key" "$env"
      return
    fi
  fi
  SKIPPED+=("Vercel env $key=$env (set it manually in the Vercel dashboard)")
  warn "skipped Vercel env $key: vercel CLI not ready; set it in the dashboard"
}

_finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=11

banner "Production deployment — Seminar Tool"

# Resolve the Vercel CLI command (global if installed, else via npx).
vercel_cmd() {
  if command -v vercel >/dev/null 2>&1; then
    printf 'vercel'
  elif command -v npx >/dev/null 2>&1; then
    printf 'npx vercel'
  else
    printf ''
  fi
}

# Log into the Vercel CLI if not already authenticated. Idempotent.
ensure_vercel_login() {
  local cmd
  cmd=$(vercel_cmd)
  if [[ -z "$cmd" ]]; then
    warn "Vercel CLI not available — set it up via the dashboard instead"
    return 1
  fi
  if $cmd whoami >/dev/null 2>&1; then
    say "Vercel CLI: already logged in"
    return 0
  fi
  say "Vercel CLI is not logged in yet — the next step opens a browser."
  say "Running: $cmd login"
  if ! $cmd login; then
    warn "Vercel login did not complete — run '$cmd login' and re-run this wizard"
    return 1
  fi
  say "Vercel CLI: logged in"
  return 0
}

# ── Stage 1: Prerequisites ───────────────────────────────────────────────
stage "Verify prerequisites"
say "Checking that required tools are available..."

MISSING=()
command -v node >/dev/null 2>&1  || MISSING+=("node")
command -v npm  >/dev/null 2>&1  || MISSING+=("npm")

if (( ${#MISSING[@]} )); then
  warn "missing: ${MISSING[*]}"
  say "Install Node.js ≥ 24 (via Volta or https://nodejs.org) and re-run."
  exit 1
fi
say "node $(node --version)  npm $(npm --version)"

if command -v docker >/dev/null 2>&1; then
  if docker info >/dev/null 2>&1; then
    say "Docker is running"
  else
    warn "Docker is installed but not running — start Docker Desktop and re-run"
    exit 1
  fi
else
  note "Docker not found (not required for production, only for local dev)"
fi

if command -v npx >/dev/null 2>&1; then
  say "npx available (for supabase / vercel CLIs)"
else
  warn "npx not found — you will need to apply migrations and deploy manually"
fi

pause "Press Enter to continue to Supabase project setup"

# ── Stage 2: Supabase project ────────────────────────────────────────────
stage "Supabase: create project"
say "Create a new Supabase project (or use an existing one)."
open_url "https://supabase.com/dashboard/projects"
step "Click 'New project' and fill in: name, database password, region."
step "Wait for the project to finish provisioning (~2 minutes)."
pause "Press Enter once your project is ready"

ask SUPABASE_PROJECT_REF "Supabase project ref (from the URL: supabase.com/dashboard/project/<ref>):"

# ── Stage 3: Supabase credentials ────────────────────────────────────────
stage "Supabase: capture credentials"
say "We need four values from the Supabase Dashboard."

# DATABASE_URL — pooled connection string
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/database"
step "Settings → Database → Connection string → URI (Pooler tab)"
step "Copy the full URI (starts with postgresql://...)"
ask_secret DATABASE_URL "Paste the pooled connection string:"

# NEXT_PUBLIC_SUPABASE_URL
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/integrations/data_api/overview"
step "Data API overview → copy the Project URL"
ask NEXT_PUBLIC_SUPABASE_URL "Paste the project URL:"

# NEXT_PUBLIC_SUPABASE_ANON_KEY
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/api-keys"
step "Settings → API Keys → publishable / anon key"
ask_secret NEXT_PUBLIC_SUPABASE_ANON_KEY "Paste the publishable / anon key:"

# SUPABASE_SERVICE_ROLE_KEY
step "Settings → API Keys → secret / service_role key"
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste the secret / service_role key:"

write_env DATABASE_URL "$DATABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_URL "$NEXT_PUBLIC_SUPABASE_URL"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEXT_PUBLIC_SUPABASE_ANON_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

# ── Stage 4: Apply migrations ────────────────────────────────────────────
stage "Apply database migrations"
say "All 12 migrations from supabase/migrations/ must be applied."
say ""
say "Option A (CLI — automated):"
say "  npx supabase login        # one-time, opens browser"
say "  npx supabase link --project-ref $SUPABASE_PROJECT_REF"
say "  npx supabase db push       # applies all migrations"
say ""
say "Option B (Dashboard — manual):"
say "  Open the SQL Editor and run each file in order."

if confirm "Use the Supabase CLI to push migrations?"; then
  if command -v npx >/dev/null 2>&1; then
    say "Running: npx supabase login"
    npx supabase login
    say "Running: npx supabase link --project-ref $SUPABASE_PROJECT_REF"
    npx supabase link --project-ref "$SUPABASE_PROJECT_REF"
    say "Running: npx supabase db push"
    npx supabase db push
    say "Migrations applied successfully"
  else
    warn "npx not available — apply migrations manually via the SQL Editor"
  fi
else
  open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/sql/new"
  say "Run each migration file in order from supabase/migrations/:"
  MIGRATION_FILES=(
    "20260824000000_init_app_health.sql"
    "20260824000001_case_types_findings_cases.sql"
    "20260824000002_releases.sql"
    "20260824000003_enable_releases_realtime.sql"
    "20260824000004_end_cases.sql"
    "20260824000005_unique_case_type_name.sql"
    "20260904000000_expire_cases.sql"
    "20260904000001_finding_images.sql"
    "20260904000002_finding_image_cleanup.sql"
    "20260910000000_rate_limits.sql"
    "20260910000001_purge_rate_limits.sql"
    "20260910000002_revoke_anon_enable_rls.sql"
  )
  for f in "${MIGRATION_FILES[@]}"; do
    step "$f"
  done
  say ""
  say "Each file: paste contents → click 'Run' → verify 'Success'."
  pause "Press Enter once all migrations are applied"
fi

# ── Stage 5: Verify pg_cron and cron jobs ────────────────────────────────
stage "Verify pg_cron and scheduled jobs"
say "The migrations install two pg_cron jobs:"
say "  1. delete-expired-cases  (daily at 03:00)"
say "  2. purge-rate-limits     (every 10 minutes)"
say ""
say "Verify in the Supabase Dashboard:"

open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/integrations/cron/jobs"
step "Database → Extensions → confirm pg_cron is enabled"
step "Database → Cron Jobs → confirm both jobs are listed and enabled"

if confirm "Are both cron jobs visible and enabled?"; then
  say "pg_cron verified"
else
  warn "Verify pg_cron manually: Dashboard → Extensions → enable pg_cron,"
  warn "then re-apply migration 20260904000000_expire_cases.sql"
fi

# ── Stage 6: Verify storage bucket ───────────────────────────────────────
stage "Verify finding-images storage bucket"
say "The migration creates a private 'finding-images' bucket with:"
say "  - file_size_limit: 10 MB"
say "  - allowed_mime_types: image/jpeg, image/png, image/webp, image/svg+xml"

open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/storage/buckets"
step "Storage → confirm 'finding-images' bucket exists and is Private"

if confirm "Does the finding-images bucket exist and is it private?"; then
  say "Storage bucket verified"
else
  warn "The bucket should have been created by migration 20260904000001_finding_images.sql"
  warn "Re-check your migrations or create it manually in the Storage dashboard"
fi

# ── Stage 7: Generate CRON_SECRET ────────────────────────────────────────
stage "Generate CRON_SECRET"
if _existing "CRON_SECRET" >/dev/null 2>&1; then
  say "CRON_SECRET already set in $ENV_FILE"
else
  CRON_SECRET=$(openssl rand -base64 32)
  write_env CRON_SECRET "$CRON_SECRET"
  say "Generated and saved CRON_SECRET"
fi

# ── Stage 7b: Set MUTATIONS_ENABLED ──────────────────────────────────────
if _existing "MUTATIONS_ENABLED" >/dev/null 2>&1; then
  note "MUTATIONS_ENABLED already set in $ENV_FILE"
else
  write_env MUTATIONS_ENABLED "true"
  note "Set MUTATIONS_ENABLED=true (required for write routes)"
fi

# ── Stage 8: Set up Vercel ───────────────────────────────────────────────
stage "Set up Vercel project"
say "Create a Vercel project for this repository. Environment variables"
say "are configured in the next stage — before the first deploy — so the"
say "build has everything it needs."

CLI_SETUP=0
if confirm "Use the Vercel CLI for guided setup?"; then
  if ensure_vercel_login; then
    VERCEL_CMD=$(vercel_cmd)
    say "Running: $VERCEL_CMD link (creates/links the project, no deploy yet)"
    $VERCEL_CMD link
    say "Vercel project linked"
    note "If you don't see a project, check: $VERCEL_CMD ls"
    CLI_SETUP=1
  else
    warn "Continue with dashboard setup instead"
    confirm "Continue with dashboard setup?" || exit 0
  fi
fi

if (( CLI_SETUP )); then
  ask VERCEL_PRODUCTION_URL "Production URL (e.g. your-project.vercel.app):"
else
  open_url "https://vercel.com/new"
  step "Import your GitHub repository (bastibuck/seminar-tool)"
  step "Framework Preset: Next.js (auto-detected)"
  step "Build & Output Settings: leave defaults"
  step "Click 'Deploy'"
  warn "The initial import build will likely FAIL because env vars aren't set"
  warn "yet — that's expected. The next stage configures them, then we deploy."
  ask VERCEL_PRODUCTION_URL "Production URL (e.g. your-project.vercel.app):"
fi
note "This is your live production URL — you will need it for smoke testing"

# ── Stage 9: Configure Vercel environment variables ──────────────────────
stage "Configure Vercel environment variables"
say "Setting production environment variables via Vercel CLI..."
say "(If the CLI is unavailable, set these in the Vercel dashboard → Settings → Environment Variables)"

UPSTREAM_ENV=(DATABASE_URL NEXT_PUBLIC_SUPABASE_URL NEXT_PUBLIC_SUPABASE_ANON_KEY SUPABASE_SERVICE_ROLE_KEY CRON_SECRET MUTATIONS_ENABLED)
for key in "${UPSTREAM_ENV[@]}"; do
  val=$(_existing "$key" || true)
  if [[ -n "$val" ]]; then
    _upsert_vercel_env "$key" "$val" "production"
  else
    warn "$key not found in $ENV_FILE — set it manually in the Vercel dashboard"
  fi
done

open_url "https://vercel.com/dashboard"
step "Settings → Environment Variables → verify all 6 variables are set for Production"

if confirm "All environment variables configured in Vercel?"; then
  say "Vercel environment variables configured"
else
  warn "Set them manually before deploying"
fi

# ── Stage 10: Deploy and verify Vercel Cron ──────────────────────────────
stage "Deploy and verify"
say "Trigger a production deployment to pick up the environment variables."

if confirm "Trigger redeploy now?"; then
  if ensure_vercel_login; then
    VERCEL_CMD=$(vercel_cmd)
    $VERCEL_CMD --prod --force
    say "Deployment triggered"
  else
    warn "Vercel CLI not available/not logged in — push to GitHub or redeploy from the dashboard"
  fi
fi

open_url "https://vercel.com/dashboard"
step "Deployments → confirm the latest deployment succeeded"
step "Settings → Cron Jobs → confirm 'finding-image-cleanup' is registered (0 3 * * *)"

if confirm "Deployment succeeded and cron job is registered?"; then
  say "Deployment and cron verified"
else
  warn "Check deployment logs in the Vercel dashboard for build errors"
fi

# ── Stage 11: Create production content ──────────────────────────────────
stage "Create production content"
say "The production database is empty — no seed data is applied automatically."
say "Create your first Case Type and Findings through the admin interface."

open_url "${VERCEL_PRODUCTION_URL:-https://vercel.com}/admin"
step "Click 'Neuer Falltyp' → enter a Case Type name → save"
step "Add Findings to the Case Type (name + image for each)"
step "Verify the Case Type and Findings appear in the list"

if confirm "Created initial Case Type and Findings?"; then
  say "Production content ready"
else
  warn "Create content before running the smoke test"
fi

# ── Final: Smoke test checklist ──────────────────────────────────────────
_clear
printf '\n%s%s  ✓ Deployment complete%s\n\n' "$BOLD" "$GREEN" "$RESET"
note "Production URL: ${VERCEL_PRODUCTION_URL:-<check Vercel dashboard>}"
note "Values written to: $ENV_FILE"
(( ${#WRITTEN_ENV[@]} )) && note "Env vars: ${WRITTEN_ENV[*]}"
(( ${#SKIPPED[@]} )) && { warn "Skipped (set manually):"; for s in "${SKIPPED[@]}"; do note "  - $s"; done; }
printf '\n'
say "Smoke test checklist:"
step "Cockpit: create a Case → verify private cockpit URL loads"
step "Viewer: enter case code → verify findings are hidden"
step "Cockpit: release a Finding → verify Viewer updates in real time"
step "Viewer: zoom/pan on finding image → verify signed URL loads"
step "Cockpit: un-release a Finding → verify Viewer hides it"
step "Cockpit: end the Case → verify Viewer shows 'Fall beendet' banner"
step "Verify released findings remain readable after case ends"
step "Vercel Cron: check /api/internal/finding-image-cleanup returns 401 without auth header"
step "Local dev: run npm run db:start && npm run dev → confirm local still works"
printf '\n'
say "After the smoke test, record the result and close issue #8."
